// Generates src/data/techIcons.ts from the `simple-icons` package (CC0 licensed).
// Only the icons listed below are embedded, so `simple-icons` stays a dev-only dependency.
// Usage: npm run icons:generate
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";

// slug -> simple-icons export name
const wanted = {
  python: "siPython",
  openjdk: "siOpenjdk",
  c: "siC",
  javascript: "siJavascript",
  html5: "siHtml5",
  css: "siCss",
  react: "siReact",
  tailwindcss: "siTailwindcss",
  gsap: "siGreensock",
  zustand: "siZustand",
  nodedotjs: "siNodedotjs",
  express: "siExpress",
  jsonwebtokens: "siJsonwebtokens",
  pandas: "siPandas",
  numpy: "siNumpy",
  matplotlib: "siMatplotlib",
  mysql: "siMysql",
  mongodb: "siMongodb",
  firebase: "siFirebase",
  googlecloud: "siGooglecloud",
  tableau: "siTableau",
  git: "siGit",
  github: "siGithub",
  postman: "siPostman",
  googlegemini: "siGooglegemini",
  nextdotjs: "siNextdotjs",
  typescript: "siTypescript",
};

const out = {};
const missing = [];
for (const [slug, key] of Object.entries(wanted)) {
  const icon = si[key];
  if (icon) out[slug] = { title: icon.title, hex: "#" + icon.hex, path: icon.path };
  else missing.push(slug);
}

const body =
  `// AUTO-GENERATED by scripts/generate-icons.mjs from simple-icons (CC0-1.0). Do not edit by hand.\n` +
  `export interface TechIcon { title: string; hex: string; path: string }\n` +
  `export const techIcons: Record<string, TechIcon> = ${JSON.stringify(out, null, 2)};\n`;
writeFileSync(new URL("../src/data/techIcons.ts", import.meta.url), body);
console.log(`Wrote ${Object.keys(out).length} icons.` + (missing.length ? ` Missing: ${missing.join(", ")}` : ""));
